#!/bin/bash

# This script is used to install all the necessary dependencies necessary
# to run a digole 2 inch lcd alongside svxlink for a real time display of
# svxlink status.

# SCRIPT CONTRIBUTORS:
# Aaron Crawford (N3MBH), Dan Loranger (KG7PAR)

#Install the needed support applications

apt-get install python-smbus python-pigpio python-pip RPi.GPIO
apt-get install python3-smbus python3-pigpio RPi.GPIO python-pip 

pip install inotify
pip3 install inotify

# Enable pigpio daemon
sudo systemctl enable pigpiod

#sudo apt-get install python3-smbus python3-pigpio  python-pip
#sudo pip3 install inotify

# make sure the LCD service is executable
sudo chmod +x LCD
# make sure the LCD script is executable
sudo chmod +x PI-REPEATER-8X.py

#move the LCD file to have it run automatically at boot
sudo mv ./LCD /etc/init.d/
cd /etc/init.d
sudo update-rc.d LCD defaults

